name: gem release
on:
  release:
    types:
      - published
jobs:
  release:
    name: check version, add tag and release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ruby
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: Create ~/.gem/credentials
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 600 $HOME/.gem/credentials
          echo "---" >$HOME/.gem/credentials
          echo ":rubygems_api_key: ${RUBYGEMS_API_KEY}" >> $HOME/.gem/credentials
      - name: update version.rb
        run: |
          cat lib/protosum2/version.rb | (rm lib/protosum2/version.rb;sed -e 's/VERSION = ".*"/VERSION = "${{github.event.release.tag_name}}"/'>lib/protosum2/version.rb)
        working-directory: ./ruby
      - name: gem build
        run: gem build *.gemspec
      - name: gem push
        run: gem push *.gem
      - name: create pr of generate code
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "gem publish"
          branch: release-gem
          base: "master"
          body: "generated by release ${{github.event.release.tagName}}"
          branch-suffix: "timestamp"
          delete-branch: true
          title: "Release gem package"
      - name: generated PR merge
        run: gh pr merge ${{ steps.cpr.outputs.pull-request-number }} -m -d
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
