name: Generate code from proto

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]

jobs:
  gen-from-proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true 
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.18.0
      - run: echo "./gobin" >> $GITHUB_PATH
      - name: install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler=3.6.1.3-2ubuntu5
      - name: generate code from proto
        run: make protogen
      - name: create pr of generate code
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'run `make protogen`'
          branch: gen-impl-from-${{github.head_ref}}
          base: 'master'
          body: 'generated by #${{ github.event.pull_request.number }}'
          delete-branch: true
          title: 'DO NOT EDIT: generate each language implementation'
      - name: check generate pr
        run: echo ${{steps.cpr.outputs.pull-request-url}}
      - name: make pr comment body
        id: pr-comment-body
        if: ${{ github.event.pull_request.merged }} == false
        run: |
          if [ -n "${{steps.cpr.outputs.pull-request-url}}" ]; then
            text="created PR of implementation from proto. URL: ${{ steps.cpr.outputs.pull-request-url }}"
          else
            text="not created PR of implementation from proto."
          fi
          echo "::set-output name=message_body::$text"
      - name: PR comment on Updating CFn Change Set
        uses: marocchino/sticky-pull-request-comment@v1
        if: ${{ github.event.pull_request.merged }} == false
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: header-of-comment
          message: ${{ steps.pr-comment-body.outputs.message_body }}
      - name: generated PR merge
        if: ${{ github.event.pull_request.merged && steps.cpr.outputs.pull-request-number}}
        run: gh pr merge ${{ steps.cpr.outputs.pull-request-number }} -m -d
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN}}
      - name: generated PR close
        if: ${{ github.event.action == 'closed' && github.event.pull_request.merged == false }}
        run: gh pr close ${{ steps.cpr.outputs.pull-request-number }} -d
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
